version: '3.8'

services:
  # Test Database
  postgres-test:
    image: postgres:16-alpine
    container_name: golfing-grouper-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: golfing_grouper_test
    ports:
      - "5433:5432"
    networks:
      - test-network
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  # API Test Service
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golfing-grouper-api-test
    command: npm test
    environment:
      NODE_ENV: test
      PORT: 5000
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_NAME: golfing_grouper_test
      DB_USER: test_user
      DB_PASSWORD: test_password
      JWT_SECRET: test_jwt_secret
      STRIPE_SECRET_KEY: test_stripe_key
      STRIPE_WEBHOOK_SECRET: test_webhook_secret
      SENDGRID_API_KEY: test_sendgrid_key
      SENDGRID_FROM_EMAIL: test@example.com
    depends_on:
      - postgres-test
    networks:
      - test-network
    volumes:
      - ./:/app
      - /app/node_modules

  # Frontend Test Service
  frontend-test:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: golfing-grouper-frontend-test
    command: npm test
    environment:
      NODE_ENV: test
      REACT_APP_API_URL: http://backend-test:5000
    depends_on:
      - backend-test
    networks:
      - test-network
    volumes:
      - ./client:/app
      - /app/node_modules

# Define networks
networks:
  test-network:
    driver: bridge

# Define volumes
volumes:
  postgres_test_data: 