version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: golfing-grouper-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-golfing_grouper_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_secure_password}
      POSTGRES_DB: ${DB_NAME:-golfing_grouper}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golfing-grouper-api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-5000}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-golfing_grouper}
      DB_USER: ${DB_USER:-golfing_grouper_user}
      DB_PASSWORD: ${DB_PASSWORD:-your_secure_password}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_here}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-your_stripe_secret_key}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-your_stripe_webhook_secret}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY:-your_sendgrid_api_key}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL:-your_verified_email@example.com}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      MODAL_URL: ${MODAL_URL:-http://localhost:3000/modal}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./:/app
      - /app/node_modules

  # React Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: golfing-grouper-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Web Scraping Service (Optional)
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golfing-grouper-scraper
    restart: unless-stopped
    command: node src/workers/scraper.js
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-golfing_grouper}
      DB_USER: ${DB_USER:-golfing_grouper_user}
      DB_PASSWORD: ${DB_PASSWORD:-your_secure_password}
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./:/app
      - /app/node_modules

# Define shared networks
networks:
  app-network:
    driver: bridge

# Define shared volumes
volumes:
  postgres_data: 